### Project specific config ###
language: generic

env:
  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta

os:
  - osx

### Install luacheck ###
install:
  - brew update
  - brew install lua
  - luarocks install luacheck

### Generic setup follows ###
script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - luacheck -v
  - ./build-package.sh

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

git:
  depth: 10

sudo: false

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
