os: Windows Server 2012 R2
platform: x64

version: "{build}"
clone_depth: 10
skip_tags: true

### Project specific config ###
environment:
  APM_TEST_PACKAGES: "linter"
  ATOM_LINT_WITH_BUNDLED_NODE: "false"

  matrix:
  - ATOM_CHANNEL: stable
  - ATOM_CHANNEL: beta

### Install luacheck ###
install:
  - appveyor DownloadFile https://dl.bintray.com/xpol/luavm/LuaVM-0.2.0-vs2015-x86.exe -FileName LuaVM.exe
  - LuaVM.exe /verysilent /dir=C:\luavm
  - set PATH=C:\luavm\luavm\versions\luajit-2.1;%PATH%
  - luarocks install luacheck

### Atom CI Generic Setup ###
build_script:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/atom/ci/master/build-package.ps1'))

test: off
deploy: off
