version: "{build}"
os: Windows Server 2012 R2

test: off
deploy: off

init:
  - cmd: rd /s /q %CHOCOLATEYINSTALL%
  - ps: iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))


cache:
  - c:\lua -> appveyor.yml
  - c:\external -> appveyor.yml

install:
  - cmd: md .appveyor
  - ps: Start-FileDownload 'https://raw.githubusercontent.com/ignacio/lua-appveyor-example/master/.appveyor/install.bat' -FileName '.appveyor/install.bat'
  - ps: Start-FileDownload 'https://raw.githubusercontent.com/ignacio/lua-appveyor-example/master/.appveyor/set_compiler_env.bat' -FileName '.appveyor/set_compiler_env.bat'
  - ps: Start-FileDownload 'https://raw.githubusercontent.com/ignacio/lua-appveyor-example/master/.appveyor/winmake.bat' -FileName '.appveyor/winmake.bat'
  - call .appveyor\set_compiler_env.bat
  - call .appveyor\install.bat
  - luarocks install luacheck
  - cinst atom -y
  - cd %APPVEYOR_BUILD_FOLDER%
  - "%LOCALAPPDATA%/atom/bin/apm install"

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - "%LOCALAPPDATA%/atom/bin/apm test --path %LOCALAPPDATA%/atom/bin/atom.cmd"
