version: "{build}"
os: Windows Server 2012 R2

test: off
deploy: off

install:
  # Install luacheck
  - appveyor DownloadFile https://dl.bintray.com/xpol/luavm/LuaVM-0.2.0-vs2015-x86.exe -FileName LuaVM.exe
  - LuaVM.exe /verysilent /dir=C:\luavm
  - set PATH=C:\luavm\luavm\versions\luajit-2.1;%PATH%
  - luarocks install luacheck
  # Install Atom
  - appveyor DownloadFile https://atom.io/download/windows -FileName AtomSetup.exe
  - AtomSetup.exe /silent
  - set PATH=%LOCALAPPDATA%\atom\bin;%PATH%
  - apm install

build_script:
  - apm test --path "%LOCALAPPDATA%/atom/bin/atom.cmd"
