version: "{build}"
os: Windows Server 2012 R2

test: off
deploy: off

environment:
  LUA_VER: 5.1.5
  LUAROCKS_VER: HEAD

cache:
  - c:\lua -> appveyor.yml
  - c:\external -> appveyor.yml

install:
  - cmd: md .appveyor
  - ps: Start-FileDownload 'https://cdn.rawgit.com/ignacio/lua-appveyor-example/0f1932a380ae29d0962db065934556edaf700794/.appveyor/install.bat' -FileName '.appveyor/install.bat'
  - ps: Start-FileDownload 'https://cdn.rawgit.com/ignacio/lua-appveyor-example/0f1932a380ae29d0962db065934556edaf700794/.appveyor/set_compiler_env.bat' -FileName '.appveyor/set_compiler_env.bat'
  - ps: Start-FileDownload 'https://cdn.rawgit.com/ignacio/lua-appveyor-example/0f1932a380ae29d0962db065934556edaf700794/.appveyor/winmake.bat' -FileName '.appveyor/winmake.bat'
  - call .appveyor\set_compiler_env.bat >NUL 2>&1
  - call .appveyor\install.bat >NUL 2>&1
  - set PATH=c:\lua\5.1.5\bin\;c:\lua\5.1.5\LuaRocks;c:\lua\5.1.5\LuaRocks\systree\bin;%PATH%
  - set PATH=c:\lua\5.1.5\bin\;c:\lua\5.1.5\LuaRocks;c:\lua\5.1.5\LuaRocks\systree\bin;%PATH%
  - set LUA_PATH=;;c:\lua\5.1.5\LuaRocks\lua\?.lua;c:\lua\5.1.5\LuaRocks\lua\?\init.lua;c:\lua\5.1.5\LuaRocks\systree\share\lua\5.1\?.lua;c:\lua\5.1.5\LuaRocks\systree\share\lua\5.1\?\init.lua
  - set LUA_CPATH=;;c:\lua\5.1.5\LuaRocks\systree\lib\lua\5.1\?.dll
  - luarocks install luacheck
  - cinst atom -y
  - cd %APPVEYOR_BUILD_FOLDER%
  - "%LOCALAPPDATA%/atom/bin/apm install"

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - "%LOCALAPPDATA%/atom/bin/apm test --path %LOCALAPPDATA%/atom/bin/atom.cmd"
